// ftextarea - JavaScript bootstrap
// Loads the WebAssembly module and initializes the application

import init from './pkg/ftextarea.js';

// Initialize the WASM module
// The init() function is generated by wasm-bindgen and handles loading the .wasm file
// Our Rust code has #[wasm_bindgen(start)] which runs automatically after init()
init().catch(err => {
    console.error('Failed to initialize ftextarea:', err);
});

// Register the service worker for offline support
if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
        navigator.serviceWorker.register('/sw.js')
            .then(registration => {
                console.log('ServiceWorker registered:', registration.scope);
            })
            .catch(err => {
                console.log('ServiceWorker registration failed:', err);
            });
    });
}

